### ISSUE TITLE
Bio not being displayed in setting page, even if there is a bio

### ISSUE THREAD

**Issue by Harsh8055** [linkcollect/Main-Website-Linkcollect#162]
Contribution Guidelines [here](https://github.com/linkcollect/Main-Website-Linkcollect/wiki/Contribution-Guidelines)

<img width="444" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/1de3627d-6ef4-4c7a-9887-28b6512de136">

But in Settings it's not showing previou outfilled bio, like other fields
<img width="1355" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/9c01c2ee-0683-4abb-8225-6b43f4983cb1">

**Comment by DarkSoul26** [comment]
Let me take a look into this @Harsh8055

**Comment by Harsh8055** [comment]
Sure

**Comment by Harsh8055** [comment]
@DarkSoul26 you looking into this ?

**Comment by MKisKrazy** [comment]
Hi @Harsh8055 . Can i look into this? Seems like a good first issue.

**Comment by Harsh8055** [comment]
hey @MKisKrazy 
sure get started ( i will assign it to you if you reply)

**Comment by MKisKrazy** [comment]
@Harsh8055 sure i ll try my best to fix it

**Comment by MKisKrazy** [comment]
@Harsh8055  i have a doubt , im not much familiar with backend. if I edited the code in my clone repo and give npm start, the app that runs is using my edited code or old code? to check if my edited code works
