### ISSUE TITLE
Bug: Invalid Password message on first visit

### ISSUE THREAD

**Issue by tushar-daiya** [linkcollect/Main-Website-Linkcollect#166]
The bug is if a user reloads the signup page the invalid password message is displayed even if the user has not input anything. 

![image](https://github.com/linkcollect/Main-Website-Linkcollect/assets/108505673/ab2e623e-c67e-4d69-8036-220b7a8957e9)

**Comment by tushar-daiya** [comment]
Can I work on this?

**Comment by aliat110** [comment]
I have fixed this issue. Please have a look

**Comment by Harsh8055** [comment]
Thanks, we will review the PR
