### ISSUE TITLE
Styling bug on User's home page

### ISSUE THREAD

**Issue by Electromorphous** [linkcollect/Main-Website-Linkcollect#171]
This bug is very visible at the bottom but I couldn't find this issue having been opened by anyone else so I'm opening this. It occurs on both Firefox and Chrome.

![image](https://github.com/linkcollect/Main-Website-Linkcollect/assets/44677718/06e1f270-3829-4749-ab9c-f819a3b40a01)

**Comment by Harsh8055** [comment]
I see, this will be fixed in the next PR.

**Comment by Harsh8055** [comment]
This was fixed, please confirm if it's fixed on your end @Electromorphous

**Comment by Electromorphous** [comment]
Yes looking good. It is fixed 👍 

However I will make a different PR fixing some minor UI bugs in general.
