### ISSUE TITLE
Z-index issue in home and saved collection page 

### ISSUE THREAD

**Issue by Harsh8055** [linkcollect/Main-Website-Linkcollect#191]
<img width="339" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/b7766e65-0b0b-489d-ae34-5693170da37e">

**Comment by Harsh8055** [comment]
@tushar-daiya i added the sortby, but facing this issue

**Comment by tushar-daiya** [comment]
Okay I will try to solve it.

**Comment by Harsh8055** [comment]
hey @tushar-daiya i fixed it in the new pr, just 1 line lol
