### ISSUE TITLE
This is a duplicate button, we need to add a tooltip saying it is duplicate in your collection

### ISSUE THREAD

**Issue by Harsh8055** [linkcollect/Main-Website-Linkcollect#194]
<img width="418" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/1c577418-9347-40a8-867a-8e6a683385e5">

**Comment by Harsh8055** [comment]
the copy looking icon is duplicate button

**Comment by Pinaka-Pani-18** [comment]
@Harsh8055 Is adding a tooltip enough to resolve this issue?
