### ISSUE TITLE
No search option in mobile view on home and saved collections page 

### ISSUE THREAD

**Issue by Harsh8055** [linkcollect/Main-Website-Linkcollect#198]
<img width="702" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/402a157b-be2c-43e9-be8c-e60acc6a7f3d">

**Comment by NsCracker** [comment]
@Harsh8055 May I proceed with this?

**Comment by Pinaka-Pani-18** [comment]
Hi can I work on this issue?

**Comment by Ayan726** [comment]
Please review this PR @Harsh8055

**Comment by Harsh8055** [comment]
Hey thanks, what doe calc do in second condition? As it was not there before

**Comment by Ayan726** [comment]
Hey @Harsh8055, actually the calc was there in the first place, please check the file before.
I didn't want to break the ui so i just changed it for the mobile view.. actually calc is calculating the space to leave from right where the sort by button is.
Anyway only w-full does the work.. should i change it and make a request? :)

**Comment by Harsh8055** [comment]
nope dude, thanks for the pr. i have another issue that i just submitted, lmk if you would wanna work on it @Ayan726
