### ISSUE TITLE
On hover on card if title or description caontains a large link it breaks the structure... use name shortner or some technique to shoe only some of the link instead, if chars in a word are more than 14-18 then crop it and show only some of it

### ISSUE THREAD

**Issue by Harsh8055** [linkcollect/Main-Website-Linkcollect#205]
open this collection, https://linkcollect.io/harshsingh.eth/c/65278d9ce7cc11eddc4f75d0
or this profile to see the bug https://linkcollect.io/harshsingh.eth

you can open it in localhost too https://localhost:3000/harshsingh.eth
<img width="789" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/39dcd7f6-9993-433f-8a41-7b443e118177">

<img width="903" alt="image" src="https://github.com/linkcollect/Main-Website-Linkcollect/assets/91266702/9c3d32f4-dfd1-441a-a7b2-7b651907bf76">

**Comment by Harsh8055** [comment]
@tushar-daiya @Ayan726 this is a major bug we need to fix :(

**Comment by Ayan726** [comment]
Hey @Harsh8055, Sure!! assign me this one .. I think for description greater than a certain number of words we can just give it a "...." at the end and finish it there.. anyone who wants to see it they can just move to the particular collection and see it.
sounds good right?

**Comment by Shariar-Hasan** [comment]
Hello @Harsh8055,
can i get this assigned under hacktoberfest?
i can do the work 😊😊
