### ISSUE TITLE
Bug: No message shown to user if wrong/duplicate bookmark data is added

### ISSUE THREAD

**Issue by ho-dor** [linkcollect/Main-Website-Linkcollect#210]
https://www.loom.com/share/e919e2c6d95d49afb21b9dbba34191ab?sid=856d9e58-83a5-4c0a-aa74-890e968a51e0

- If I add a duplicate link to the bookmark, api returns 400 but no error message is shown to user. It's a bad user experience

**Comment by Harsh8055** [comment]
hey i see, you we are using toaster library, what you can do is if it fails, show a toast with error message.. link already exist. also, the error messages needs to be added in more places that we need to find out

**Comment by ho-dor** [comment]
@Harsh8055 will raise a fix
