### ISSUE TITLE
Collection Page / Bookmark Component

### ISSUE THREAD

**Issue by tusharverma06** [linkcollect/Main-Website-Linkcollect#48]
We need to create the below **Link Component** in our project to enhance functionality.

 **Please follow clean code practices while implementing the component to ensure maintainability and readability.**

![image](https://github.com/linkcollect/Main-Website-Linkcollect/assets/117444846/4c821ee8-0dad-4acd-86b7-7db8350cd726)

here's the figma link for reference: https://www.figma.com/file/8AdVJeP4j8CoNODccUCyaS/LinkCollect-Dev?type=design&node-id=1%3A4430&t=0WOeDDbpQXjMoiTr-1

### Instructions : 
- Fork this repo 
- create a new branch
- make a new folder in components folder and name it collectionCardV2
- Once done create a pr with brief description(image/video) explaining your work, comparing with v2 branch.**

###  Congratulations you are a **Contributor of Linkcollect  🎉🎉**!!

**Comment by ItsApex** [comment]
Ye mei kr du :)

**Comment by tusharverma06** [comment]
> Ye mei kr du :)

ho gya ser next pe karlo abhi post karrha hu
