### ISSUE TITLE
Bookmarks Page / Linkcomponent

### ISSUE THREAD

**Issue by tusharverma06** [linkcollect/Main-Website-Linkcollect#50]
**We need to create the below Link Component in our project to enhance functionality.**

**Please follow clean code practices while implementing the component to ensure maintainability and readability.**

![image](https://github.com/linkcollect/Main-Website-Linkcollect/assets/117444846/31a00127-b0b6-43b9-b3ad-3d5480e8d1b3)

here's the figma link for reference: 
https://www.figma.com/file/8AdVJeP4j8CoNODccUCyaS/LinkCollect-Dev?type=design&node-id=57%3A1327&t=ZGeCJIAWXBthHfG7-1

### Instructions :

- Fork this repo
- create a new branch
- make a new folder in components folder and name it BookmarkItemV2
- Once done create a pr with brief description(image/video) explaining your work, comparing with v2 branch.

### Congratulations you are a Contributor of Linkcollect 🎉🎉!!

**Comment by Mudassirkhan2** [comment]
@tusharverma06      this figma file link doesn't exit

**Comment by tusharverma06** [comment]
### New figma file:

https://www.figma.com/file/Bs7pAJuwE3yZY49zaRiCbS/Dev-LinkCollect?type=design&node-id=2601-3286&t=1hRkdky1m1jzxHkg-0

**Comment by subhradwip01** [comment]
The issue is closed as the basic function is done..and UI will be implemented by another issue #55
